name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: print greeting
       run: | 
           echo "hello world"
           echo "this is my world"
     - name: print goodbye
       run: echo "this is my departure message"
